project:
  type: website
  output-dir: docs
  preview: 
      browser: true
      port: 4088

website:
  title: "Abhijnya Bhat"
  favicon: profile.png
  twitter-card: true
  page-footer: 
    left: 'Credits: <a href="https://github.com/vibhamasti/vibhamasti.github.io" target="_blank">[1]</a> and <a href="https://github.com/elizabethmcd/elizabethmcd.github.io" target="_blank">[2]</a> '
    right: This website was made with &#10084; using <a href="https://quarto.org/" target="_blank">Quarto</a>.
  navbar:
    right:
      - pubs.qmd
      # - teaching.qmd
      # - posts.qmd
      # - text: Resume
      #   href: resumes/Resume_VibhaMasti.pdf
        # external: true
      # - icon: envelope-fill
      #   href: mailto:vsmasti@gmail.com
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/vibha-masti/
      # - icon: youtube
      #   href: https://www.youtube.com/@VibhaMasti
      # - icon: github
      #   href: https://github.com/vibhamasti
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    # link-external-icon: true
    # link-external-newwindow: true
    from: markdown+emoji
    theme: solar
    css: styles.scss



